// @ts-nocheck -- skip type checking
import * as docs_7 from "../content/blogs/turbo-repo-monorepo-guide.mdx?collection=docs&hash=1742395109163"
import * as docs_6 from "../content/blogs/react-hook-form-guide.mdx?collection=docs&hash=1742395109163"
import * as docs_5 from "../content/blogs/nextjs-server-actions-tutorial.mdx?collection=docs&hash=1742395109163"
import * as docs_4 from "../content/blogs/index.mdx?collection=docs&hash=1742395109163"
import * as docs_3 from "../content/blogs/elysiajs-nextjs-integration.mdx?collection=docs&hash=1742395109163"
import * as docs_2 from "../content/blogs/create-your-own-authentication-system.mdx?collection=docs&hash=1742395109163"
import * as docs_1 from "../content/blogs/auth-from-scratch.mdx?collection=docs&hash=1742395109163"
import * as docs_0 from "../content/blogs/arch-linux-hyprland-setup.mdx?collection=docs&hash=1742395109163"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"arch-linux-hyprland-setup.mdx","absolutePath":"/home/tiesen/Documents/portfolio/content/blogs/arch-linux-hyprland-setup.mdx"}, data: docs_0 }, { info: {"path":"auth-from-scratch.mdx","absolutePath":"/home/tiesen/Documents/portfolio/content/blogs/auth-from-scratch.mdx"}, data: docs_1 }, { info: {"path":"create-your-own-authentication-system.mdx","absolutePath":"/home/tiesen/Documents/portfolio/content/blogs/create-your-own-authentication-system.mdx"}, data: docs_2 }, { info: {"path":"elysiajs-nextjs-integration.mdx","absolutePath":"/home/tiesen/Documents/portfolio/content/blogs/elysiajs-nextjs-integration.mdx"}, data: docs_3 }, { info: {"path":"index.mdx","absolutePath":"/home/tiesen/Documents/portfolio/content/blogs/index.mdx"}, data: docs_4 }, { info: {"path":"nextjs-server-actions-tutorial.mdx","absolutePath":"/home/tiesen/Documents/portfolio/content/blogs/nextjs-server-actions-tutorial.mdx"}, data: docs_5 }, { info: {"path":"react-hook-form-guide.mdx","absolutePath":"/home/tiesen/Documents/portfolio/content/blogs/react-hook-form-guide.mdx"}, data: docs_6 }, { info: {"path":"turbo-repo-monorepo-guide.mdx","absolutePath":"/home/tiesen/Documents/portfolio/content/blogs/turbo-repo-monorepo-guide.mdx"}, data: docs_7 }], [{ info: {"path":"meta.json","absolutePath":"/home/tiesen/Documents/portfolio/content/blogs/meta.json"}, data: {"pages":["...","!index"]} }])