import { toRuntime, toRuntimeAsync } from "fumadocs-mdx"
import * as docs_0 from "../content/blogs/arch-linux-hyprland-setup.mdx?collection=docs&hash=999f836af5f88a33edd41faf2a83fd1c"
import * as docs_1 from "../content/blogs/auth-from-scratch.mdx?collection=docs&hash=999f836af5f88a33edd41faf2a83fd1c"
import * as docs_2 from "../content/blogs/elysiajs-nextjs-integration.mdx?collection=docs&hash=999f836af5f88a33edd41faf2a83fd1c"
import * as docs_3 from "../content/blogs/index.mdx?collection=docs&hash=999f836af5f88a33edd41faf2a83fd1c"
import * as docs_4 from "../content/blogs/nextjs-server-actions-tutorial.mdx?collection=docs&hash=999f836af5f88a33edd41faf2a83fd1c"
import * as docs_5 from "../content/blogs/pytorch-cnn-image-classification.mdx?collection=docs&hash=999f836af5f88a33edd41faf2a83fd1c"
import * as docs_6 from "../content/blogs/react-hook-form-guide.mdx?collection=docs&hash=999f836af5f88a33edd41faf2a83fd1c"
import * as docs_7 from "../content/blogs/turbo-repo-monorepo-guide.mdx?collection=docs&hash=999f836af5f88a33edd41faf2a83fd1c"
export const docs = [toRuntime("doc", docs_0, {"path":"arch-linux-hyprland-setup.mdx","absolutePath":"/home/tiesen/Documents/portfolio/content/blogs/arch-linux-hyprland-setup.mdx"}), toRuntime("doc", docs_1, {"path":"auth-from-scratch.mdx","absolutePath":"/home/tiesen/Documents/portfolio/content/blogs/auth-from-scratch.mdx"}), toRuntime("doc", docs_2, {"path":"elysiajs-nextjs-integration.mdx","absolutePath":"/home/tiesen/Documents/portfolio/content/blogs/elysiajs-nextjs-integration.mdx"}), toRuntime("doc", docs_3, {"path":"index.mdx","absolutePath":"/home/tiesen/Documents/portfolio/content/blogs/index.mdx"}), toRuntime("doc", docs_4, {"path":"nextjs-server-actions-tutorial.mdx","absolutePath":"/home/tiesen/Documents/portfolio/content/blogs/nextjs-server-actions-tutorial.mdx"}), toRuntime("doc", docs_5, {"path":"pytorch-cnn-image-classification.mdx","absolutePath":"/home/tiesen/Documents/portfolio/content/blogs/pytorch-cnn-image-classification.mdx"}), toRuntime("doc", docs_6, {"path":"react-hook-form-guide.mdx","absolutePath":"/home/tiesen/Documents/portfolio/content/blogs/react-hook-form-guide.mdx"}), toRuntime("doc", docs_7, {"path":"turbo-repo-monorepo-guide.mdx","absolutePath":"/home/tiesen/Documents/portfolio/content/blogs/turbo-repo-monorepo-guide.mdx"})];
export const meta = [];