interface OpenGraphProps {
  appName?: string
  logo?: React.ReactNode
  title?: string
  description?: string
  caption?: string
  image?: string
  primaryColor?: string
  corner?: { margin?: number; length?: number; strokeWidth?: number }
  style?: React.CSSProperties
}

function OpenGraph({
  appName = 'My App',
  caption = `Generated by ${appName}`,
  primaryColor = '#3f5ec2',
  ...props
}: OpenGraphProps) {
  const corner = { margin: 24, length: 52, strokeWidth: 1, ...props.corner }
  const s = corner.strokeWidth / 2
  const max = corner.length - s
  const mutedColor = '#a4a4a4'
  const isImageOnly = !props.title && !props.description

  const truncatedTitle = props.title
    ? props.title.length > 35
      ? props.title.slice(0, 32) + '...'
      : props.title
    : ''
  const truncatedDescription = props.description
    ? props.description.length > 160
      ? props.description.slice(0, 157) + '...'
      : props.description
    : ''

  const Corner = ({
    position,
    path,
  }: {
    position: React.CSSProperties
    path: string
  }) => (
    <svg
      style={{
        position: 'absolute',
        width: corner.length,
        height: corner.length,
        pointerEvents: 'none',
        ...position,
      }}
      viewBox={`0 0 ${corner.length} ${corner.length}`}
    >
      <path
        d={path}
        fill='none'
        stroke={`${mutedColor}40`}
        strokeWidth={corner.strokeWidth}
        strokeLinecap='round'
        strokeLinejoin='round'
      />
    </svg>
  )

  return (
    <div
      style={{
        position: 'relative',
        width: '1200px',
        height: '630px',
        padding: '3.5rem',
        backgroundColor: '#000000',

        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: '2.5rem',
        ...props.style,
      }}
    >
      <div
        style={{
          position: 'absolute',
          width: '100%',
          height: '100%',

          backgroundSize: '48px 48px',
          backgroundImage: `
            linear-gradient(to right, ${mutedColor}20 1px, transparent 1px),
            linear-gradient(to bottom, ${mutedColor}20 1px, transparent 1px)
          `,

          maskImage:
            'radial-gradient(circle at center, black 20%, transparent 100%)',
          WebkitMaskImage:
            'radial-gradient(circle at center, black 20%, transparent 100%)',

          pointerEvents: 'none',
        }}
      />

      <Corner
        position={{ top: corner.margin, left: corner.margin }}
        path={`M ${corner.length} ${s} L ${s} ${s} L ${s} ${corner.length}`}
      />

      <Corner
        position={{ top: corner.margin, right: corner.margin }}
        path={`M 0 ${s} L ${max} ${s} L ${max} ${corner.length}`}
      />

      <Corner
        position={{ bottom: corner.margin, left: corner.margin }}
        path={`M ${s} 0 L ${s} ${max} L ${corner.length} ${max}`}
      />

      <Corner
        position={{ bottom: corner.margin, right: corner.margin }}
        path={`M ${max} 0 L ${max} ${max} L 0 ${max}`}
      />

      <div
        style={{
          flex: 1,
          display: isImageOnly ? 'none' : 'flex',
          flexDirection: 'column',
          width: '100%',
          height: '100%',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: '1.25rem' }}>
          {props.logo && (
            <div
              style={{
                width: '52px',
                height: '52px',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                border: `1px solid ${primaryColor}80`,
                borderRadius: '16px',
                overflow: 'hidden',
              }}
            >
              {props.logo}
            </div>
          )}

          <h2
            style={{
              fontSize: '1.5rem',
              fontWeight: 600,
              letterSpacing: '1px',
              color: primaryColor,
              textTransform: 'uppercase',
              margin: 0,
            }}
          >
            {appName}
          </h2>
        </div>

        <div
          className='line-clamp-2'
          style={{
            flex: 1,
            display: 'flex',
            flexDirection: 'column',
            alignItems: props.image ? 'flex-start' : 'center',
            justifyContent: 'center',
            gap: '1.75rem',
          }}
        >
          <h1
            style={{
              textAlign: props.image ? 'left' : 'center',
              fontSize: '3.75rem',
              fontWeight: 700,
              lineHeight: '1.15',
              color: '#ffffff',
              margin: 0,
            }}
          >
            {truncatedTitle}
          </h1>

          <p
            style={{
              textAlign: props.image ? 'left' : 'center',
              fontSize: '1.875rem',
              fontWeight: 400,
              lineHeight: '1.5',
              color: mutedColor,
              margin: 0,
            }}
          >
            {truncatedDescription}
          </p>
        </div>
      </div>

      {props.image && (
        <div
          style={{
            flexShrink: 0,
            display: 'flex',
            width: isImageOnly ? '560px' : '400px',
            height: isImageOnly ? '315px' : '400px',
            border: `1px solid ${primaryColor}80`,
            borderRadius: '1rem',
            overflow: 'hidden',
          }}
        >
          {/* oxlint-disable-next-line next/no-img-element */}
          <img
            src={props.image}
            alt={props.title}
            style={{
              objectFit: 'cover',
              width: '100%',
              height: '100%',
              borderRadius: '1rem',
            }}
          />
        </div>
      )}

      <div
        style={{
          display: 'flex',
          position: 'absolute',
          bottom: corner.margin - 8,
          right: corner.margin + corner.length + 8,
        }}
      >
        <p
          style={{
            fontSize: '0.875rem',
            fontWeight: 400,
            color: mutedColor,
            margin: 0,
          }}
        >
          {caption}
        </p>
      </div>
    </div>
  )
}

export { OpenGraph }
