name: Preview
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - 'apps/web/**'

concurrency:
  group: pr-preview-${{ github.event.pull_request.number }}
  cancel-in-progress: false

jobs:
  deploy-preview:
    if: ${{ github.event.action != 'closed' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: ./tools/github/actions/setup

      - name: Build Shadcn Registry
        run: bun --filter @yuki/web build:shadcn

      - name: Deploy Preview
        run: bun --filter @yuki/web cf:deploy --stage pr-${{ github.event.pull_request.number }}
        env:
          GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          ALCHEMY_PASSWORD: ${{ secrets.ALCHEMY_PASSWORD }}
          ALCHEMY_STATE_TOKEN: ${{ secrets.ALCHEMY_STATE_TOKEN }}

          APP_URL: ${{ secrets.APP_URL }}
          RESEND_TOKEN: ${{ secrets.RESEND_TOKEN }}

  cleanup-preview:
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: ./tools/github/actions/setup

      - name: Cleanup Preview
        run: bun --filter @yuki/web cf:destroy --stage pr-${{ github.event.pull_request.number }}
        env:
          GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          ALCHEMY_PASSWORD: ${{ secrets.ALCHEMY_PASSWORD }}
          ALCHEMY_STATE_TOKEN: ${{ secrets.ALCHEMY_STATE_TOKEN }}

          APP_URL: ${{ secrets.APP_URL }}
          RESEND_TOKEN: ${{ secrets.RESEND_TOKEN }}
