name: Publish
on:
  push:
    branches:
      - main
    paths:
      - 'apps/web/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./tools/github/actions/setup

      - name: Deploy to Production
        run: bun --filter @yuki/web cf:deploy --stage prod
        env:
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          ALCHEMY_PASSWORD: ${{ secrets.ALCHEMY_PASSWORD }}
          ALCHEMY_STATE_TOKEN: ${{ secrets.ALCHEMY_STATE_TOKEN }}

          APP_URL: ${{ secrets.APP_URL }}
          RESEND_TOKEN: ${{ secrets.RESEND_TOKEN }}
